### ISSUE TITLE
Customcert error send email certificate

### ISSUE THREAD

**Issue by MaurizioBelli** [mdjnelson/moodle-mod_customcert#528] opened 2022-12-14 17:53 UTC
I get the following error when cron tries to send certificates via email
customcert version 4.0.1 (2022041901) in moodle 4.0.2 ( 20220711)

Execute scheduled task: Gestisce l'invio dei certificati via email (mod_customcert\task\email_certificate_task)
... started 22:25:08. Current memory use 2.7 MB.
... used 48 dbqueries
... used 0.060248136520386 seconds
Scheduled task failed: Gestisce l'invio dei certificati via email (mod_customcert\task\email_certificate_task),È stato rilevato un errore di programmazione, deve essere sistemato da un programmatore: Context does not belong to any course.
Backtrace:
* line 1540 of /lib/enrollib.php: call to context->get_course_context()
* line 1454 of /lib/enrollib.php: call to get_enrolled_join()
* line 1508 of /lib/enrollib.php: call to get_enrolled_with_capabilities_join()
* line 1631 of /lib/enrollib.php: call to get_enrolled_sql()
* line 96 of /mod/customcert/classes/task/email_certificate_task.php: call to get_enrolled_users()
* line 253 of /lib/cronlib.php: call to mod_customcert\task\email_certificate_task->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 81 of /admin/cron.php: call to cron_run()

**Comment by mdjnelson** [comment] 2023-03-10 10:48
Closing as a duplicate of #443.

**Closed by mdjnelson** 2023-03-10 10:48 UTC
