### ISSUE TITLE
Moodle 4.0: cannot drag elements to their position

### ISSUE THREAD

**Issue by Urpokarhu1** [mdjnelson/moodle-mod_customcert#514] opened 2022-09-09 05:57 UTC
Hello,

there is a bug in custom certificate 3.11.1 (2021051701) & Moodle 4.0 when you add an element to certificate and open reposition elements 

A) you can drag the element but it always resets to default position 
or
B) if you are lucky and manage  drag it to another position it sticks to it.

https://user-images.githubusercontent.com/53904029/189281203-61583f45-4b7e-4984-a4aa-f7ded981b0be.mp4

**Comment by Urpokarhu1** [comment] 2022-09-09 06:01
the bug might be in javascript working in background that recognizes the area you can drag elements to @mdjnelson

**Comment by Urpokarhu1** [comment] 2022-09-09 06:06
also if you press "save and continue" the element goes here

![image](https://user-images.githubusercontent.com/53904029/189282278-b4b32bbc-798a-4b15-885c-7b62ef3736bc.png)

**Comment by alihamas575** [comment] 2022-09-10 09:30
Thank you so much for taking the time to post a video of the problem.
I read a post by mdjelson. In the Moodle Forums it was written:
I no longer work as a moodle code developer. If someone can post a pull request I can delegate github. etc. things like
https://moodle.org/mod/forum/discuss.php?d=433425#p1760598
Unfortunately, it will stay that way for a long time, maybe forever.

**Comment by mdjnelson** [comment] 2022-09-12 02:16
Closing as a duplicate of #513. Thanks for showing the video of what is happening. As @alihamas575 stated I would very much appreciate a pull request.

**Closed** 2022-09-12 02:16 UTC
Labels: duplicate
