### ISSUE TITLE
Certificate is being issued to Non editing teachers automatically

### ISSUE THREAD

**Issue by adanisyrex** [mdjnelson/moodle-mod_customcert#519] opened 2022-10-21 08:56 UTC
Hi all, I am having the problem that the custom cert is issuing certificates to Non editing teachers automatically. I thought that to receive a Certificate you must be student.
I also have set a condition that the student must have a calification in an evaluation test.
It is not the case since the Non editing teacher is receiving a certificate without even have the evaluation test done.
Why is that happening and any clue of how can a fixed it? Thanks in advance

I mean, Custom cert is issuing a certificate to a Non editing teacher without even have pass the evaluation test and even without being a student on the course.

I am using Moodle 3.5 (Build: 20180517)
Custom Cert version: 3.5.9 2018051710

**Comment by mdjnelson** [comment] 2023-05-30 07:12
Closing as a duplicate of #360.

**Closed by mdjnelson** 2023-05-30 07:12 UTC
