### ISSUE TITLE
Behat test failing - managing_elements.feature

### ISSUE THREAD

**Issue by AdilIqbal95** [mdjnelson/moodle-mod_customcert#496] opened 2022-05-06 15:40 UTC
Hi, the test stated above is failing.

**Environment details:**
MySQL 5.7
PHP 7.4
Moodle latest MOODLE_311_STABLE

**Error details:**
And I add the element "User field" to page "1" of the "Custom certificate 1" certificate template: debugging() message/s found:
Invalid get_string() identifier: 'skype' or component 'moodle'. Perhaps you are missing $string['skype'] = ''; in lang/en/moodle.php?
line 353 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 606 of /user/classes/fields.php: call to get_string()
line 55 of /mod/customcert/element/userfield/classes/element.php: call to core_user\fields::get_display_name()
line 68 of /mod/customcert/classes/edit_element_form.php: call to customcertelement_userfield\element->render_form_elements()
line 214 of /lib/formslib.php: call to mod_customcert\edit_element_form->definition()
line 79 of /mod/customcert/edit_element.php: call to moodleform->__construct()
 (Exception)

**Comment by mdjnelson** [comment] 2023-03-11 05:18
Closing as a duplicate of https://github.com/mdjnelson/moodle-mod_customcert/issues/497 which contains more details.

**Closed by mdjnelson** 2023-03-11 05:18 UTC
Labels: duplicate
