### ISSUE TITLE
Allow the ability to obtain the PDF in different ways

### ISSUE THREAD

**Issue by DavidDelco** [mdjnelson/moodle-mod_customcert#405] opened 2021-02-06 19:19 UTC
Hallo!
It's probably not an issue, but it's still a problem in my case.
When the user downloads their certificate, the .pdf version is opened in the same browser window and when users close it they are off the platform .... could you allow the opening in a new tab (Blank)?
Thank you.

**Comment by mdjnelson** [comment] 2021-02-09 01:04
Take a look at the options at https://github.com/moodle/moodle/blob/master/lib/pdflib.php#L183.

**Comment by mdjnelson** [comment] 2021-02-22 04:41
Sorry, that was more a comment for me when I start working on this. I will need to allow options for the people creating the certificate how they want it to be displayed.

**Comment by mdjnelson** [comment] 2021-02-23 12:15
Closing as a duplicate of #401.

**Closed** 2021-02-23 12:15 UTC

**Comment by mdjnelson** [comment] 2021-04-05 08:47
Fixing #401 now for anyone watching this issue.
