### ISSUE TITLE
All source releases are incorrectly packaged according the to Moodle release checks

### ISSUE THREAD

**Issue by kiklop74** [mdjnelson/moodle-mod_customcert#441] opened 2021-07-13 12:59 UTC
Whenever a plugin release is provided the root directory inside the archive should be equal to the plugin name. Here we have root directory named moodle-mod_customcert-[release tag] instead of just having customcert.

Can we expect this to be rectified at some point?

Thanks

**Comment by leonstr** [comment] 2021-07-14 09:32
It looks like this was caused by a bug in the Plugins Directory: [MDLSITE-6525](https://tracker.moodle.org/browse/MDLSITE-6525). Other plugins were affected too, for example: [mod_checklist](https://moodle.org/plugins/mod_checklist#comment-71573-60eea7fd37b47), [format_grid](https://moodle.org/mod/forum/discuss.php?d=424140#p1708407). The issue is shown as fixed but presumably plugin authors must upload a new zip file to replace the one with the wrong directory name.

**Comment by mdjnelson** [comment] 2021-07-16 02:53
Thanks @leonstr for mentioning that. I am going to close this issue now, it will be fixed by next release when I upload a new version.

**Closed by mdjnelson** 2021-07-16 02:53 UTC
