### ISSUE TITLE
Feature request: search from issued certificates

### ISSUE THREAD

**Issue by Urpokarhu1** [mdjnelson/moodle-mod_customcert#397] opened 2020-12-15 09:47 UTC
Hello,

I would like to see feature where you could search by firstname and lastname from the issued certificates, its hard to find them if you have hunderds of issued certificates

**Comment by mdjnelson** [comment] 2020-12-23 08:29
Closing as a duplicate of #31. I see you commented there already. If you have a code solution please submit it and I will view it.

**Closed by mdjnelson** 2020-12-23 08:29 UTC
