### ISSUE TITLE
customcert

### ISSUE THREAD

**Issue by slydrone** [mdjnelson/moodle-mod_customcert#527] opened 2022-12-13 08:52 UTC
Hi I'm having the following issue. 4.0.1 (2022041901)  [Moodle](http://moodle.org/) [4.0.5+ (Build: 20221122)](http://docs.moodle.org/dev/Releases)
PHP Notice:  Coding problem: unsupported modification of PAGE->context from 70 to 70* line 1193 of /lib/pagelib.php: call to debugging()
* line 90 of /mod/customcert/classes/task/email_certificate_task.php: call to moodle_page->set_context()
* line 253 of /lib/cronlib.php: call to mod_customcert\task\email_certificate_task->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()
 in /home/challengetrg/public_html/moodle/lib/weblib.php on line 3268

**Comment by leonstr** [comment] 2022-12-15 17:31
Duplicate of both #443 and #501?

**Comment by TopSolid** [comment] 2023-01-18 07:37
> Duplicate of both #443 and #501?

Yes indeed.

**Comment by mdjnelson** [comment] 2023-03-10 10:45
Closing as it is a duplicate.

**Closed** 2023-03-10 10:45 UTC
