### ISSUE TITLE
Write the username within the pdf file name to sort better

### ISSUE THREAD

**Issue by benutzer-prog** [mdjnelson/moodle-mod_customcert#393] opened 2020-11-30 12:40 UTC
It would be great to write the username in the name of the pdf file. As administrator I download the sent certificates and move them to another directory, but instead of opening each certificate it would be great to be able to read the username in the filename of the certificate.
Any suggestions how to do this?

Kind regards,

Ben

**Comment by mdjnelson** [comment] 2020-12-02 04:01
You can't currently do this. In order to do this you will have to edit the code at https://github.com/mdjnelson/moodle-mod_customcert/blob/MOODLE_310_STABLE/classes/template.php#L256 to change the filename. I am closing this as it is not an issue I will be working on, nor does it provide a viable option. A setting for deciding how the PDF is named would work but needs more discussion. What if the user wants the course full name in the PDF name? It's hard providing that flexibility via a setting. It needs code changes.

**Comment by mdjnelson** [comment] 2020-12-02 06:49
I'll reopen just because people have requested having the ability to rename the PDF but I am not sure how to achieve this so it is flexible and will be usable by everyone.

**Comment by mdjnelson** [comment] 2021-02-03 10:55
Closing as duplicate of #132.

**Closed by mdjnelson** 2021-02-03 10:55 UTC
Labels: duplicate
