### ISSUE TITLE
Column 'moodle_customcert.templateid' is invalid.  Not contained in either an aggregate function or the GROUP BY clause.

### ISSUE THREAD

**Issue by ZXRoxas** [mdjnelson/moodle-mod_customcert#649] opened 2024-10-18 15:18 UTC
Execute scheduled task: Issue certificates task (mod_customcert\task\issue_certificates_task)
... started 19:11:25. Current memory use 29.3 MB.
Debugging increased temporarily due to faildelay of 86400
... used 1 dbqueries
... used 2.8524348735809 seconds
Scheduled task failed: Issue certificates task (mod_customcert\task\issue_certificates_task),Error reading from database (SQLState: 42000<br>
Error Code: 8120<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'moodle_customcert.templateid' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.<br>

SELECT c.id, c.templateid, c.course, c.requiredtime, c.emailstudents, c.emailteachers, c.emailothers,
                       ct.id AS templateid, ct.name AS templatename, ct.contextid, co.id AS courseid,
                       co.fullname AS coursefullname, co.shortname AS courseshortname
                  FROM moodle_customcert c
                  JOIN moodle_customcert_templates ct
                    ON c.templateid = ct.id
                  JOIN moodle_course co
                    ON c.course = co.id
                  JOIN moodle_course_categories cat
                    ON co.category = cat.id
             LEFT JOIN moodle_customcert_issues ci
                    ON c.id = ci.customcertid WHERE (c.emailstudents = '1'
                     OR c.emailteachers = '1'
                     OR  LEN(c.emailothers) >= 3) AND co.visible = 1 AND cat.visible = 1 AND (co.enddate > '1697681485' OR (co.enddate = 0 AND ci.timecreated > '1697681485')) GROUP BY c.id, ct.id, ct.name, ct.contextid, co.id, co.fullname, co.shortname
[array (
  0 => 1,
  1 => 1,
  2 => 1697681485,
  3 => 1697681485,
)])
Debug info:
SQLState: 42000<br>
Error Code: 8120<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'moodle_customcert.templateid' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.<br>

SELECT c.id, c.templateid, c.course, c.requiredtime, c.emailstudents, c.emailteachers, c.emailothers,
                       ct.id AS templateid, ct.name AS templatename, ct.contextid, co.id AS courseid,
                       co.fullname AS coursefullname, co.shortname AS courseshortname
                  FROM moodle_customcert c
                  JOIN moodle_customcert_templates ct
                    ON c.templateid = ct.id
                  JOIN moodle_course co
                    ON c.course = co.id
                  JOIN moodle_course_categories cat
                    ON co.category = cat.id
             LEFT JOIN moodle_customcert_issues ci
                    ON c.id = ci.customcertid WHERE (c.emailstudents = '1'
                     OR c.emailteachers = '1'
                     OR  LEN(c.emailothers) >= 3) AND co.visible = 1 AND cat.visible = 1 AND (co.enddate > '1697681485' OR (co.enddate = 0 AND ci.timecreated > '1697681485')) GROUP BY c.id, ct.id, ct.name, ct.contextid, co.id, co.fullname, co.shortname
[array (
  0 => 1,
  1 => 1,
  2 => 1697681485,
  3 => 1697681485,
)]
Backtrace:
* line 331 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
* line 438 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
* line 909 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
* line 985 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
* line 94 of \mod\customcert\classes\task\issue_certificates_task.php: call to sqlsrv_native_moodle_database->get_records_sql()
* line 410 of \lib\classes\cron.php: call to mod_customcert\task\issue_certificates_task->execute()
* line 208 of \lib\classes\cron.php: call to core\cron::run_inner_scheduled_task()
* line 125 of \lib\classes\cron.php: call to core\cron::run_scheduled_tasks()
* line 186 of \admin\cli\cron.php: call to core\cron::run_main_process()

**Comment by eiconsult** [comment] 2024-10-18 15:47
I was able to resolve this by doing so:

MSSQL is a bit strict with Group By functions and requires columns be listed in the group by statement if it is referenced in the select statement. In this case, the c.* retrieves all columns in the select statement. 


Potential "**quick**" workaround

line 91: \mod\customcert\classes\task\issue_certificates_task.php

from: 
`$sql .= " GROUP BY c.id, ct.id, ct.name, ct.contextid, co.id, co.fullname, co.shortname";`

to: 
`$sql .= " GROUP BY c.id, ct.id, ct.name, ct.contextid, co.id, co.fullname, co.shortname, c.course,c.templateid,c.intro,c.introformat,c.requiredtime, c.name,              ,c.verifyany,c.emailstudents,c.emailteachers,c.emailothers,c.protection,c.timecreated,c.timemodified,c.deliveryoption,c.language";`

**Comment by eiconsult** [comment] 2024-10-18 15:48
> Plugin Version: 4.4.3 (2024042207). Moodle Version: 4.4.3+ (Build: 20240920).


I was able to resolve this by doing so:

MSSQL is a bit strict with Group By functions and requires columns be listed in the group by statement if it is referenced in the select statement. In this case, the c.* retrieves all columns in the select statement.

Potential "quick" workaround

line 91: \mod\customcert\classes\task\issue_certificates_task.php

from:
$sql .= " GROUP BY c.id, ct.id, ct.name, ct.contextid, co.id, co.fullname, co.shortname";

to:
$sql .= " GROUP BY c.id, ct.id, ct.name, ct.contextid, co.id, co.fullname, co.shortname, c.course,c.templateid,c.intro,c.introformat,c.requiredtime, c.name,              ,c.verifyany,c.emailstudents,c.emailteachers,c.emailothers,c.protection,c.timecreated,c.timemodified,c.deliveryoption,c.language";

**Comment by mdjnelson** [comment] 2024-10-18 15:56
@eiconsult can you try with the latest version which includes https://github.com/mdjnelson/moodle-mod_customcert/commit/44250554e3dd74c31d06816930c94dec90f7ffeb? I dont have access to an easily accessible SQL database without a bunch of docker configurations? If you can provide a diff, or even a PR that would be great.

**Comment by eiconsult** [comment] 2024-10-18 16:00
Ah. You've got it. I see 2024042206 replaced with 2024042207.

I'll drop a note when confirmed

-Eseosa


________________________________

**Comment by mdjnelson** [comment] 2024-10-21 14:20
Hey @eiconsult, any update? :) Would like to fix this if it wasn't actually fixed by the patch I listed.

**Comment by eiconsult** [comment] 2024-10-21 14:27
:) client owns the MSSQL service. It will take a few to get this situated.



Thank you
-Eseosa

________________________________

**Comment by mdjnelson** [comment] 2024-10-21 15:46
Some time on the weekend ill get Moodle docker setup and run it against MSSQL and Oracle. I've just been too lazy to do that. 😅

**Comment by rlowry** [comment] 2024-11-05 09:01
Unfortunately the Oracle patch does not fix this for SQL Server. With v4.4.3 installed I still get the following error:

`Execute scheduled task: Issue certificates task (mod_customcert\task\issue_certificates_task)
... started 00:48:54. Current memory use 38.0 MB.
Debugging increased temporarily due to faildelay of 86400
... used 1 dbqueries
... used 0.41620993614197 seconds
Scheduled task failed: Issue certificates task (mod_customcert\task\issue_certificates_task),Error reading from database (SQLState: 42000<br>
Error Code: 8120<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'mdl_customcert.templateid' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.<br>

SELECT c.id, c.templateid, c.course, c.requiredtime, c.emailstudents, c.emailteachers, c.emailothers,
                       ct.id AS templateid, ct.name AS templatename, ct.contextid, co.id AS courseid,
                       co.fullname AS coursefullname, co.shortname AS courseshortname
                  FROM mdl_customcert c
                  JOIN mdl_customcert_templates ct
                    ON c.templateid = ct.id
                  JOIN mdl_course co
                    ON c.course = co.id
                  JOIN mdl_course_categories cat
                    ON co.category = cat.id
             LEFT JOIN mdl_customcert_issues ci
                    ON c.id = ci.customcertid WHERE (c.emailstudents = '1'
                     OR c.emailteachers = '1'
                     OR  LEN(c.emailothers) >= 3) AND co.visible = 1 AND cat.visible = 1 AND (co.enddate > '1699231734' OR (co.enddate = 0 AND ci.timecreated > '1699231734')) GROUP BY c.id, ct.id, ct.name, ct.contextid, co.id, co.fullname, co.shortname
[array (
  0 => 1,
  1 => 1,
  2 => 1699231734,
  3 => 1699231734,
)])
Debug info:
SQLState: 42000<br>
Error Code: 8120<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'mdl_customcert.templateid' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.<br>

SELECT c.id, c.templateid, c.course, c.requiredtime, c.emailstudents, c.emailteachers, c.emailothers,
                       ct.id AS templateid, ct.name AS templatename, ct.contextid, co.id AS courseid,
                       co.fullname AS coursefullname, co.shortname AS courseshortname
                  FROM mdl_customcert c
                  JOIN mdl_customcert_templates ct
                    ON c.templateid = ct.id
                  JOIN mdl_course co
                    ON c.course = co.id
                  JOIN mdl_course_categories cat
                    ON co.category = cat.id
             LEFT JOIN mdl_customcert_issues ci
                    ON c.id = ci.customcertid WHERE (c.emailstudents = '1'
                     OR c.emailteachers = '1'
                     OR  LEN(c.emailothers) >= 3) AND co.visible = 1 AND cat.visible = 1 AND (co.enddate > '1699231734' OR (co.enddate = 0 AND ci.timecreated > '1699231734')) GROUP BY c.id, ct.id, ct.name, ct.contextid, co.id, co.fullname, co.shortname
[array (
  0 => 1,
  1 => 1,
  2 => 1699231734,
  3 => 1699231734,
)]
Backtrace:
* line 331 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
* line 438 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
* line 909 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
* line 985 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
* line 94 of \mod\customcert\classes\task\issue_certificates_task.php: call to sqlsrv_native_moodle_database->get_records_sql()
* line 410 of \lib\classes\cron.php: call to mod_customcert\task\issue_certificates_task->execute()
* line 208 of \lib\classes\cron.php: call to core\cron::run_inner_scheduled_task()
* line 125 of \lib\classes\cron.php: call to core\cron::run_scheduled_tasks()
* line 186 of \admin\cli\cron.php: call to core\cron::run_main_process()`

**Comment by arborrow** [comment] 2024-12-09 11:54
Mark - FYI, I am also experiencing this on the JRS Moodle server. Peace - Anthony

**Comment by kdima71** [comment] 2024-12-09 16:31
Most likely, your task in this sql query is to arrange (sort) the data, instead of aggregating, so use ORDER BY instead of GROUP BY.

**Comment by arborrow** [comment] 2024-12-19 15:02
Mark - I was overly optimistic. The create certificates task wasn't scheduled to run. I am still receiving the issue.

Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'mdl_customcert.templateid' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.<br>

 

SELECT c.id, c.templateid, c.course, c.requiredtime, c.emailstudents, c.emailteachers, c.emailothers,

                       ct.id AS templateid, ct.name AS templatename, ct.contextid, co.id AS courseid,

                       co.fullname AS coursefullname, co.shortname AS courseshortname

                  FROM mdl_customcert c

                  JOIN mdl_customcert_templates ct

                    ON c.templateid = ct.id

                  JOIN mdl_course co

                    ON c.course = co.id

                  JOIN mdl_course_categories cat

                    ON co.category = cat.id

             LEFT JOIN mdl_customcert_issues ci

                    ON c.id = ci.customcertid WHERE (c.emailstudents = '1'

                     OR c.emailteachers = '1'

                     OR  LEN(c.emailothers) >= 3) AND co.visible = 1 AND cat.visible = 1 AND (co.enddate > '1703081035' OR (co.enddate = 0 AND ci.timecreated > '1703081035')) GROUP BY c.id, ct.id, ct.name, ct.contextid, co.id, co.fullname, co.shortname

[array (

  0 => 1,

  1 => 1,

  2 => 1703081035,

  3 => 1703081035,

)])

Debug info:

SQLState: 42000<br>

Error Code: 8120<br>

Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'mdl_customcert.templateid' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.<br>

 

SELECT c.id, c.templateid, c.course, c.requiredtime, c.emailstudents, c.emailteachers, c.emailothers,

                       ct.id AS templateid, ct.name AS templatename, ct.contextid, co.id AS courseid,

                       co.fullname AS coursefullname, co.shortname AS courseshortname

                  FROM mdl_customcert c

                  JOIN mdl_customcert_templates ct

                    ON c.templateid = ct.id

                  JOIN mdl_course co

                    ON c.course = co.id

                  JOIN mdl_course_categories cat

                    ON co.category = cat.id

             LEFT JOIN mdl_customcert_issues ci

                    ON c.id = ci.customcertid WHERE (c.emailstudents = '1'

                     OR c.emailteachers = '1'

                     OR  LEN(c.emailothers) >= 3) AND co.visible = 1 AND cat.visible = 1 AND (co.enddate > '1703081035' OR (co.enddate = 0 AND ci.timecreated > '1703081035')) GROUP BY c.id, ct.id, ct.name, ct.contextid, co.id, co.fullname, co.shortname

[array (

  0 => 1,

  1 => 1,

  2 => 1703081035,

  3 => 1703081035,

)]

Backtrace:

* line 331 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()

* line 438 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()

* line 907 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()

* line 983 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()

* line 94 of \mod\customcert\classes\task\issue_certificates_task.php: call to sqlsrv_native_moodle_database->get_records_sql()

* line 263 of \lib\cronlib.php: call to mod_customcert\task\issue_certificates_task->execute()

* line 120 of \lib\cronlib.php: call to cron_run_inner_scheduled_task()

* line 73 of \lib\cronlib.php: call to cron_run_scheduled_tasks()

* line 178 of \admin\cli\cron.php: call to cron_run()

**Comment by arborrow** [comment] 2024-12-19 15:11
I'm happy to test a fix. FYI, I'm working with Moodle 4.1, Custom Certificate 4.1.7, 2022112814.

**Comment by mdjnelson** [comment] 2024-12-31 17:25
Closing, will deal with this in #646.

**Closed by mdjnelson** 2024-12-31 17:25 UTC

**Comment by arborrow** [comment] 2025-01-10 11:06
Mark - It looks like both #649 and #646 are marked as closed but the issue for MSSQL remains. I'm happy to test if there is a solution you would me to try. Peace - Anthony

**Comment by mdjnelson** [comment] 2025-01-11 13:35
#646 is still open. I am fixing it today. :)
