### ISSUE TITLE
Invalid course module ID

### ISSUE THREAD

**Issue by hlindsell** [mdjnelson/moodle-mod_customcert#391] opened 2020-11-25 11:39 UTC
Hi i have been trying to tackle this error for over 3 months now.  I have tried all the suggestions on the moodle forum.  Can anybody please help? Please note, the certificates for all our other courses are working fine; it is just for this one particular course when you click 'view certificate' upon completion of the course.

![error](https://user-images.githubusercontent.com/75021025/100222795-83acf880-2f12-11eb-9c2b-f1ce5cfcd97e.png)

**Comment by mdjnelson** [comment] 2020-11-25 12:16
This has been reported many times in the forum and I really should look into it. I swear there was an existing issue for this but only found https://github.com/mdjnelson/moodle-mod_customcert/issues/34 which is the same error but caused by something else.

I am in quarantine right now as I recently flew from Spain to Australia and literally can not leave this hotel room for 14 days so I will get time to work on this. However, replication steps would really help. Do you know what you did? Is it a duplicate certificate? Is it from a backup/restore? The more details the better because I can't fix it unless I can replicate it.

Thanks. :)

**Comment by mdjnelson** [comment] 2020-11-25 12:18
Ok, I can't seem to find any of the reported instances on the forum, so maybe I imagined it. I did however find your forum post and saw no one was able to help you. Again, replication steps are needed.

**Comment by hlindsell** [comment] 2020-11-25 14:44
Hello Mark 😊

How do we know it is caused by something else when I don’t even know what caused this error?

Sorry to hear you are in quarantine but glad to hear you got to travel a bit!

The problem stems back to early September and as I am very new in this role I don’t have much of a clue what I actually did.  I was trying to edit some slides in the course as one of our users complained.  They asked me to sort out slides 2 and 3 (which were apparently blank) so I imagine I may have tried to delete those two slides and they asked me to get the links working on slides 12, 15 and 27.

I most likely referred to these links: https://docs.moodle.org/19/en/Add/edit_courses , https://www.youtube.com/watch?v=PrProtbMdRQ&t=99s ,

It is not a duplicate certificate, neither is it from a backup/restore.

Kind regards,


Heleni Lindsell
Systems Improvement Officer

Tel: 02476 786 620

[cid:image003.png@01D6C339.7E0642A0]

**Comment by hlindsell** [comment] 2020-11-25 15:01
In reply to: 'The error is being thrown because Moodle can not find the activity details'

Do you think it has anything to do with activity completion then?

I don’t know if this screenshot helps at all but notice the ticks in the boxes for the interactive course and not the simplified course :S – not sure what this is about as error comes up for both courses.

**Comment by hlindsell** [comment] 2020-11-25 15:03
![image](https://user-images.githubusercontent.com/75021025/100244849-528ef100-2f2f-11eb-8c02-528bff8bb205.png)


![image](https://user-images.githubusercontent.com/75021025/100244910-5fabe000-2f2f-11eb-83dd-199be40b12d1.png)

**Comment by hlindsell** [comment] 2020-11-25 15:21
The changes I made in September time are as follows:

  *   [cid:image003.png@01D6C33D.FEA75990]

[cid:image004.png@01D6C33D.FEA75990]


  *   [cid:image001.png@01D6C33E.50A15F70]

Same red messages as above.

  *   [cid:image002.png@01D6C33E.92B34860]

Same red messages as above.


So I imagine it has got something to do with this……….?

Best regards


Heleni

**Comment by hlindsell** [comment] 2020-11-27 10:00
Hi Mark,

Are you able to see all my messages in reply to your last comment above?  Have you been able to look into our issue at all?

Kind regards,

Heleni

**Comment by mdjnelson** [comment] 2020-11-27 10:39
```
How do we know it is caused by something else when I don’t even know what caused this error?
```

Because the stack trace is completely different (see the first image you posted where it lists the stack trace).

One of your posts has no images attached, please see https://github.com/mdjnelson/moodle-mod_customcert/issues/391#issuecomment-733771562.

I have not had time to look at this. I have been busy releasing new versions and updating this plugin for 3.9 and 3.10. Please note I am doing this in my spare time, this is not my full-time job.

**Comment by hlindsell** [comment] 2020-11-27 12:19
ok, apologies Mark.  Thank you for letting me know.  It is also worth noting that this error happened post migration.  When we tried pointing the config file back to the old database the certificates were fine.

Kind regards,

Heleni

**Comment by hlindsell** [comment] 2020-11-27 12:22
also, apologies re no images (you can tell i'm an amateur right).  Hopefully this time it works:
![image](https://user-images.githubusercontent.com/75021025/100449076-3617c380-30ab-11eb-8f08-00c2e726a4ca.png)

**Comment by hlindsell** [comment] 2020-11-27 12:48
I imagine it's something to do with this...
![image](https://user-images.githubusercontent.com/75021025/100450995-8fcdbd00-30ae-11eb-9228-ae6aeb0c04c0.png)
where i've updated the grade with a different id number...
have no idea what I was doing but think this might be the culprit......thoughts?

**Comment by hlindsell** [comment] 2020-12-08 09:36
Hello Mark, just wondering if you had had a chance to look at the above atall?
Kind regards,
Heleni

**Comment by mdjnelson** [comment] 2020-12-09 05:24
Apologies but I have not. I have just been let out of quarantine and am sorting out my life right now. I am also quite in debt due to the expenses of travelling during COVID (and the 2 weeks hotel cost which is mandatory in Australia) so have been working to make some $$ I desperately need. :) I hope once I am over this hill I can begin working on this project more.

**Comment by hlindsell** [comment] 2020-12-09 08:39
Hi Mark,

Not a problem at all.  Thank you very much for keeping me in the picture and all the best for getting back on track :)

**Comment by mdjnelson** [comment] 2024-03-19 16:22
Going through this again and I couldnt replicate it unless I intentionally went into the database and broke the data. I have a feeling that is what happened here but happy to proven wrong. Also, since the plugin is widely used and I have not heard any other complains I am closing as I cannot reproduce. If it is still an issue let me know.

**Closed by mdjnelson** 2024-03-19 16:22 UTC
