### ISSUE TITLE
Placement of course name in certificate

### ISSUE THREAD

**Issue by imijwn** [mdjnelson/moodle-mod_customcert#399] opened 2020-12-22 12:43 UTC
If a course name is too long, it is displayed to the very edge of the page on the certificate. If a break occurs, the name is not displayed in the center, but left-sided (see screenshot). 

In the certificate setting itself there is no further possibility to set it to centered when breaking (see screenshot):

![Umbruch_Kursname_Zertifikat](https://user-images.githubusercontent.com/75747053/102889790-91936200-445b-11eb-8bb3-6f667c35f496.png)
![Zertifikat_Einstellung](https://user-images.githubusercontent.com/75747053/102889800-9526e900-445b-11eb-9a9a-f037c78f25a4.png)

**Comment by mdjnelson** [comment] 2021-02-15 12:57
So would the idea here be for Testverlangerung to be in the center as well?

**Comment by amenk** [comment] 2021-02-15 14:00
@mdjnelson 

Thanks for your reply - yes, that is the idea. Is this possible?

(I am a colleague of @imijwn)

**Comment by mdjnelson** [comment] 2021-04-05 12:23
I need to check the TCPDF library to see if it supports this.

**Comment by mdjnelson** [comment] 2021-07-20 03:59
Closing as a duplicate of https://github.com/mdjnelson/moodle-mod_customcert/issues/121.

**Closed by mdjnelson** 2021-07-20 03:59 UTC
