### ISSUE TITLE
I want people to immediately download the certificate instead of inlining it online

### ISSUE THREAD

**Issue by TomVerheijen** [mdjnelson/moodle-mod_customcert#411] opened 2021-03-02 11:46 UTC
I would like to have my certificate settings back to what it was. Now it shows the certificate online, but I would like my certificate to be downloaded by my students.

**Comment by mdjnelson** [comment] 2021-03-02 13:47
Closing as a duplicate of #401.

**Closed** 2021-03-02 13:48 UTC
Labels: duplicate
