### ISSUE TITLE
Change text alignment on certificate

### ISSUE THREAD

**Issue by ckaine** [mdjnelson/moodle-mod_customcert#439] opened 2021-07-05 05:31 UTC
Hi, 
I am wanting to change the text alignment for a custom text field on the certificate to be centred rather than left justified, is this possible? See highlighted image attached

![image](https://user-images.githubusercontent.com/86944684/124422043-ccc70400-dda1-11eb-94cd-15c104ace5a4.png)

**Comment by mdjnelson** [comment] 2021-07-12 10:25
Closing as a duplicate of #121 (which I have increased priority of).

**Closed** 2021-09-13 20:24 UTC
Labels: duplicate
