### ISSUE TITLE
The user filter is required in the list of users who have received a certificate. 

### ISSUE THREAD

**Issue by jrojas-garrido** [mdjnelson/moodle-mod_customcert#622] opened 2024-05-27 16:18 UTC
The user filter is required in the list of users who have received a certificate. 

I have more than 8000 certificates issued and finding a user by their first and last name is complicated.  Although the issued certificates are displayed in alphabetical order of the user and there is a page layout, it would be ideal to have the same filters of 'enrol users' to find a certificate and reprint it.

**Comment by mdjnelson** [comment] 2024-05-27 16:20
I thought of this a long time ago I just haven't worked on it as it takes some time.

Closing as this is a duplicate of https://github.com/mdjnelson/moodle-mod_customcert/issues/31.

**Closed by mdjnelson** 2024-05-27 16:20 UTC

**Comment by jrojas-garrido** [comment] 2024-05-27 16:24
@mdjnelson thank you for the info. I will talk with our developper @Tsheke
