### ISSUE TITLE
Expiry Dates

### ISSUE THREAD

**Issue by i-am-sheep** [mdjnelson/moodle-mod_customcert#499] opened 2022-05-24 16:55 UTC
Hi Mark 

I love this plug in, thank you so much for it. We've been using it for years.

 I'm wondering if you are planning to add the expiry date feature that the new Workplace Certificates (which I know are based on your code) have?

Cheers

**Comment by IntrovertHedgehog** [comment] 2022-05-30 01:56
Hi. I am not Mark but I have created this function. I will make a pull request in several day after the testing.

Personally it is working just fine. If you need an installable .zip I can send it to you

**Comment by i-am-sheep** [comment] 2022-05-30 14:18
oh wow, that is great news, thank you

**Comment by IntrovertHedgehog** [comment] 2022-05-31 02:15
This is the zip file. It's not very conventional but workable. I will notify you when production-grade version is ready.
[customcert.zip](https://github.com/mdjnelson/moodle-mod_customcert/files/8801500/customcert.zip)

**Comment by i-am-sheep** [comment] 2022-05-31 11:02
That's great, thank you very much, I'll give it a try

**Comment by BLKLearning** [comment] 2023-05-03 19:48
@IntrovertHedgehog Is it possible to use your modification but have it set the expiry date for 2 years from the date of course completion for example?

**Comment by mdjnelson** [comment] 2024-03-19 18:39
Closing as a duplicate of https://github.com/mdjnelson/moodle-mod_customcert/issues/195.

**Comment by mdjnelson** [comment] 2024-03-19 18:43
Also expiry dates were added in https://github.com/mdjnelson/moodle-mod_customcert/pull/389 but it's very limited.

**Comment by mdjnelson** [comment] 2024-03-19 21:37
Reopening. I have decided to close #195 as there was a PR associated with it which I have used. This issue can be used to improve the current behaviour.

**Comment by mdjnelson** [comment] 2024-03-21 11:25
Is the consensus here just to add a date picker so a user can specify an exact date? We already have expiry dates for 1 - 5 years and am wondering how that should change.

**Comment by mdjnelson** [comment] 2024-03-21 14:58
Ping @i-am-sheep.

**Comment by i-am-sheep** [comment] 2024-04-03 14:29
I'm happy with just 1-5 years but it would be great if you could add it to the verification page

**Comment by leonstr** [comment] 2024-07-23 16:11
Added PR #633 with a proposed implementation of this.

**Comment by mdjnelson** [comment] 2024-08-26 10:24
Code is up not on GitHub. I'll be releasing it on the plugins DB shortly.

**Closed by mdjnelson** 2024-08-26 10:24 UTC
Labels: enhancement, Waiting for response

**Comment by animaux** [comment] 2024-09-27 13:31
Dear @mdjnelson, are the expiry dates really limited to a range of 1–5 years? We would need half a year for us to use this on a semester basis. Is it possible to use this?

Apparently we are using an older version without expiration date support. As a normal user it looks like I’m not able to check the version number.

**Comment by mdjnelson** [comment] 2024-09-28 15:11
Could you please create a new issue to introduce this? Right now it is only yearly.
