### ISSUE TITLE
 PDF and Image for Custom Certificate

### ISSUE THREAD

**Issue by rudykartson** [mdjnelson/moodle-mod_customcert#617] opened 2024-05-15 13:32 UTC
I'm currently using the Custom certificate plugin in moodle 4.3 ([Moodle Custom certificate plugin]). I'd like to understand:

1. PDF Storage Location: Where are the generated PDF certificates stored after a user successfully completes the process?
2. Image Generation: Is it possible to automatically generate an image of the certificate alongside the PDF during the backend process?
3, Image Display in Certificate Section: If I customize the certificate section of my Moodle site, could I potentially display the generated image there?

Please advice if somebody has done this.

**Comment by mdjnelson** [comment] 2024-05-15 15:57
Closing as this is not a bug but a question. I will answer in the certificate forum when I am next available.

**Closed by mdjnelson** 2024-05-15 15:57 UTC

**Comment by mdjnelson** [comment] 2024-05-15 15:59
Link to forum for reference - https://moodle.org/mod/forum/discuss.php?d=458480.
