### ISSUE TITLE
Feature Request: Group name

### ISSUE THREAD

**Issue by dheuring** [mdjnelson/moodle-mod_customcert#317] opened 2019-12-19 08:22 UTC
There is currently a option to add the "course name" to a certificate. Any chance the "group name" can also be included as an option? Thanks so much for this cool plugin!

**Comment by mdjnelson** [comment] 2019-12-20 09:32
Thanks for the report. Am closing due to it being a duplicate of #155.

**Closed by mdjnelson** 2019-12-20 09:32 UTC
